os: osx
osx_image: xcode10
before_install:
  - brew update
  - brew upgrade node
  - brew install npm
  - brew install ios-deploy
  - npm install -g appium
  - pip3 install Appium-Python-Client
  #- python setup.py install
#language: python
#python:
#  - "3.6"
# command to install dependencies
#install:
#  - pip install -r requirements.txt
# command to run tests
script:
  - echo "hello world"
  # - nohup appium > myprogram.out &
  # - nohup appium > myprogram.out &
  # - nohup appium > myprogram.out &
  - appium &
  - sleep 7s
  - cat myprogram.out 
  - ls -l
  - cat myprogram.out
  - cd myFolder
  - cat myprogram.out
  - python3 simulatorTest.py
  - cat myprogram.out
